### ISSUE TITLE
header will occupy 100% height of the screen on Safari

### ISSUE THREAD

**Issue by dinghr537** [IKMLab/IKMLab.github.io#13]
Environment: 
- macOS 11.2.2
- Safari 14.0.3 (16610.4.3.1.4)

How to Reproduce:
- open the lab's website with Safari

<img width="651" alt="issue example" src="https://user-images.githubusercontent.com/47959869/129536602-007ba1e4-06e3-47cb-b7ae-75508a181b27.png">

**Comment by ProFatXuanAll** [comment]
Fix in #15
